//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthcareAssistant
    {
        public int AssistantId { get; set; }
        public string AssistantName { get; set; }
        public string ProfessionName { get; set; }
        public int DepartmentId { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
