//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGetPatientDetail
    {
        public string PatientName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public long ContactNumber { get; set; }
        public string Address { get; set; }
        public string DoctorName { get; set; }
        public string treatment { get; set; }
        public string DepartmentName { get; set; }
        public string AssistantName { get; set; }
    }
}
